//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFood.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public Pedido()
        {
            this.Boleta = new HashSet<Boleta>();
            this.Producto = new HashSet<Producto>();
        }
    
        public int id_pedido { get; set; }
        public string descripcion { get; set; }
        public int valor { get; set; }
        public System.DateTime fecha { get; set; }
        public string estado { get; set; }
        public int usuario_id_usuario { get; set; }
    
        public virtual ICollection<Boleta> Boleta { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
