//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFood.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int id_usuario { get; set; }
        public string usuario1 { get; set; }
        public string password { get; set; }
        public string titular { get; set; }
        public string rut { get; set; }
        public int tipoUsuario { get; set; }
    
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
